#pragma once

#define NK_INCLUDE_FIXED_TYPES
#define NK_INCLUDE_STANDARD_IO
#define NK_INCLUDE_DEFAULT_ALLOCATOR
#define NK_INCLUDE_VERTEX_BUFFER_OUTPUT
#define NK_INCLUDE_FONT_BAKING
#define NK_INCLUDE_DEFAULT_FONT
#define NK_INCLUDE_STANDARD_VARARGS

#define MAX_VERTEX_MEMORY 512 * 1024
#define MAX_ELEMENT_MEMORY 128 * 1024

#include <SDL.h>

#ifdef USE_GLES
#define NK_SDL_GLES2_IMPLEMENTATION 1
#include <SDL_opengles2.h>
#else
#define NK_SDL_GL3_IMPLEMENTATION 1
#include <SDL_opengl.h>
#endif

#include <nuklear.h>
