name: Emscripten (WebGL)

on:
  push:
    branches:
    - Init
  pull_request:
    branches:
    - Init

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"
        
    - name: Apt Update
      run: sudo apt update
    - name: Get Submodules
      run: git submodule update --init
    - name: Premake Compile
      run: premake5 --os=emscripten --file=build/premake5.lua gmake
    - name: Compile (emscripten)
      run: git clone https://github.com/emscripten-core/emsdk.git && cd emsdk && ./emsdk install latest && ./emsdk activate latest && source ./emsdk_env.sh && cd ../ && make
