name: Emscripten (WebGL)

on:
  push:
    branches:
    - Init
  pull_request:
    branches:
    - Init

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Apt Update
      run: sudo apt update
    - name: Apt Install
      run: sudo apt install ninja-build --yes --quiet
    - name: Get Submodules
      run: git submodule update --init
    - name: Install Emscripten SDK
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        echo "source $PWD/emsdk_env.sh" >> $GITHUB_ENV
    
    - name: Set up Emscripten Environment
      run: source emsdk/emsdk_env.sh
    
    - name: Generate Makefiles with Premake
      run: premake5 --os=emscripten --file=build/premake5.lua gmake
    
    - name: Compile with emmake + make
      run: emmake make
