name: MacOS (Arm64) - OpenGL

on:
  push:
    branches:
      - Init
  pull_request:
    branches:
      - Init

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta2"
      
      - name: Get Submodules
        run: git submodule update --init
      - name: Compile (Premake)
        run: |
          premake5 --os=macosx --file=build/premake5.lua gmake
          make
