name: Windows - OpenGL

on:
  push:
    branches:
      - Init
  pull_request:
    branches:
      - Init

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2

      - name: Setup OpenCL development environment
        run: |
          choco install opencl-intel-cpu-runtime -y
          
          New-Item -ItemType Directory -Force -Path "C:\OpenCL\include"
          New-Item -ItemType Directory -Force -Path "C:\OpenCL\lib"
          
          Invoke-WebRequest -Uri "https://github.com/KhronosGroup/OpenCL-Headers/archive/refs/heads/main.zip" -OutFile "headers.zip"
          Expand-Archive -Path "headers.zip" -DestinationPath "temp"
          Copy-Item -Path "temp\OpenCL-Headers-main\CL" -Destination "C:\OpenCL\include" -Recurse
          
          echo "OPENCL_ROOT=C:\OpenCL" >> $env:GITHUB_ENV
          echo "OPENCL_INCLUDE_DIRS=C:\OpenCL\include" >> $env:GITHUB_ENV
        
      - uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta2"

      - name: Get Submodules
        run: git submodule update --init

      - name: Compile (Premake)
        run: |
          premake5 --os=windows --file=build/premake5.lua vs2022
          msbuild program-solution.sln /p:Configuration=Debug /p:Platform=x64
