name: Windows - OpenGL
on:
  push:
    branches:
      - Init
      - OS
  pull_request:
    branches:
      - Init
      - OS

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta2"

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_image
            curl
            unzip

      - name: Get Submodules
        run: git submodule update --init

      - name: Setup OpenCL headers
        shell: msys2 {0}
        run: |
          curl -L "https://github.com/KhronosGroup/OpenCL-Headers/archive/refs/heads/main.zip" -o opencl-headers.zip
          unzip opencl-headers.zip
          mkdir -p /mingw64/include
          cp -r OpenCL-Headers-main/CL /mingw64/include/
          rm -rf opencl-headers.zip OpenCL-Headers-main

      - name: Install OpenCL runtime
        run: choco install opencl-intel-cpu-runtime -y

      - name: Generate Makefiles
        run: |
          premake5 --os=windows --file=build/premake5.lua gmake

      - name: Build with make
        shell: msys2 {0}
        run: |
          echo "Trying to detect make..."
          if command -v make >/dev/null 2>&1; then
              echo "Found 'make'"
              make
          elif command -v mingw32-make >/dev/null 2>&1; then
              echo "Found 'mingw32-make'"
              mingw32-make
          elif command -v gmake >/dev/null 2>&1; then
              echo "Found 'gmake'"
              gmake
          else
              echo "No make variant found!"
              exit 1
          fi
